# Generated by Django 2.2.6 on 2019-10-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=20, unique=True)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
